version: '3.1'

services:
    mongo:
        image: mongo:5
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGODB_DATABASE: pokemon-db
        volumes:
            - ./mongo:/data/db
